"use client";

import type { ComponentType, SVGProps } from "react";
import {
  Activity,
  ArrowRightLeft,
  Bell,
  ChevronDown,
  ChevronLeft,
  FolderKanban,
  GripVertical,
  Home,
  Inbox,
  LayoutDashboard,
  LayoutGrid,
  MessageSquare,
  MoreHorizontal,
  Plus,
  Save,
  Search,
  Settings,
  SlidersHorizontal,
  Users,
  Workflow,
  X,
} from "lucide-react";
import {
  IconActivity,
  IconAdjustmentsHorizontal,
  IconArrowsExchange,
  IconBell,
  IconChevronDown,
  IconChevronLeft,
  IconDeviceFloppy,
  IconDots,
  IconFolder,
  IconGripVertical,
  IconHierarchy,
  IconHome,
  IconInbox,
  IconLayoutDashboard,
  IconLayoutGrid,
  IconMessage,
  IconPlus,
  IconSearch,
  IconSettings,
  IconUsers,
  IconX,
} from "@tabler/icons-react";
import {
  Pulse as PhPulse,
  ArrowsLeftRight as PhArrowsLeftRight,
  Bell as PhBell,
  CaretDown as PhCaretDown,
  CaretLeft as PhCaretLeft,
  ChatCircle as PhChatCircle,
  DotsSixVertical as PhDotsSixVertical,
  DotsThree as PhDotsThree,
  FloppyDisk as PhFloppyDisk,
  Folder as PhFolder,
  GearSix as PhGearSix,
  GitBranch as PhGitBranch,
  House as PhHouse,
  Layout as PhLayout,
  MagnifyingGlass as PhMagnifyingGlass,
  Plus as PhPlus,
  SlidersHorizontal as PhSlidersHorizontal,
  SquaresFour as PhSquaresFour,
  Tray as PhTray,
  Users as PhUsers,
  X as PhX,
} from "@phosphor-icons/react";
import {
  AdjustmentsHorizontalIcon,
  ArrowDownTrayIcon,
  ArrowPathRoundedSquareIcon,
  ArrowRightCircleIcon,
  Bars3Icon,
  BellIcon,
  ChatBubbleLeftIcon,
  ChevronDownIcon,
  ChevronLeftIcon,
  Cog6ToothIcon,
  FolderIcon,
  HomeIcon,
  InboxIcon,
  MagnifyingGlassIcon,
  PlusIcon,
  Squares2X2Icon,
  UsersIcon,
  XMarkIcon,
} from "@heroicons/react/24/outline";
import type { IconSetId } from "@/lib/appearance/appearance";
import type { IconName } from "@/lib/appearance/icon-names";

export type IconComponent = ComponentType<
  SVGProps<SVGSVGElement> & { className?: string }
>;

function phosphorIcon(
  Icon: ComponentType<{ className?: string; weight?: "regular" }>,
): IconComponent {
  return function PhosphorWrapped({ className }: SVGProps<SVGSVGElement>) {
    return <Icon className={className} weight="regular" />;
  };
}

const LUCIDE: Record<IconName, IconComponent> = {
  "nav.home": Home,
  "nav.board": LayoutGrid,
  "nav.inbox": Inbox,
  "nav.more": MoreHorizontal,
  "nav.pulse": LayoutDashboard,
  "nav.people": Users,
  "nav.notices": Bell,
  "nav.settings": Settings,
  "nav.project": FolderKanban,
  "nav.studios": Activity,
  "action.close": X,
  "action.filter": SlidersHorizontal,
  "action.chevron-down": ChevronDown,
  "action.chevron-left": ChevronLeft,
  "action.plus": Plus,
  "action.search": Search,
  "action.grip": GripVertical,
  "action.move-column": ArrowRightLeft,
  "action.comment": MessageSquare,
  "action.save": Save,
  "action.workflow": Workflow,
};

const TABLER: Record<IconName, IconComponent> = {
  "nav.home": IconHome,
  "nav.board": IconLayoutGrid,
  "nav.inbox": IconInbox,
  "nav.more": IconDots,
  "nav.pulse": IconLayoutDashboard,
  "nav.people": IconUsers,
  "nav.notices": IconBell,
  "nav.settings": IconSettings,
  "nav.project": IconFolder,
  "nav.studios": IconActivity,
  "action.close": IconX,
  "action.filter": IconAdjustmentsHorizontal,
  "action.chevron-down": IconChevronDown,
  "action.chevron-left": IconChevronLeft,
  "action.plus": IconPlus,
  "action.search": IconSearch,
  "action.grip": IconGripVertical,
  "action.move-column": IconArrowsExchange,
  "action.comment": IconMessage,
  "action.save": IconDeviceFloppy,
  "action.workflow": IconHierarchy,
};

const PHOSPHOR: Record<IconName, IconComponent> = {
  "nav.home": phosphorIcon(PhHouse),
  "nav.board": phosphorIcon(PhSquaresFour),
  "nav.inbox": phosphorIcon(PhTray),
  "nav.more": phosphorIcon(PhDotsThree),
  "nav.pulse": phosphorIcon(PhLayout),
  "nav.people": phosphorIcon(PhUsers),
  "nav.notices": phosphorIcon(PhBell),
  "nav.settings": phosphorIcon(PhGearSix),
  "nav.project": phosphorIcon(PhFolder),
  "nav.studios": phosphorIcon(PhPulse),
  "action.close": phosphorIcon(PhX),
  "action.filter": phosphorIcon(PhSlidersHorizontal),
  "action.chevron-down": phosphorIcon(PhCaretDown),
  "action.chevron-left": phosphorIcon(PhCaretLeft),
  "action.plus": phosphorIcon(PhPlus),
  "action.search": phosphorIcon(PhMagnifyingGlass),
  "action.grip": phosphorIcon(PhDotsSixVertical),
  "action.move-column": phosphorIcon(PhArrowsLeftRight),
  "action.comment": phosphorIcon(PhChatCircle),
  "action.save": phosphorIcon(PhFloppyDisk),
  "action.workflow": phosphorIcon(PhGitBranch),
};

const HERO: Record<IconName, IconComponent> = {
  "nav.home": HomeIcon,
  "nav.board": Squares2X2Icon,
  "nav.inbox": InboxIcon,
  "nav.more": Bars3Icon,
  "nav.pulse": Squares2X2Icon,
  "nav.people": UsersIcon,
  "nav.notices": BellIcon,
  "nav.settings": Cog6ToothIcon,
  "nav.project": FolderIcon,
  "nav.studios": ArrowPathRoundedSquareIcon,
  "action.close": XMarkIcon,
  "action.filter": AdjustmentsHorizontalIcon,
  "action.chevron-down": ChevronDownIcon,
  "action.chevron-left": ChevronLeftIcon,
  "action.plus": PlusIcon,
  "action.search": MagnifyingGlassIcon,
  "action.grip": Bars3Icon,
  "action.move-column": ArrowRightCircleIcon,
  "action.comment": ChatBubbleLeftIcon,
  "action.save": ArrowDownTrayIcon,
  "action.workflow": ArrowPathRoundedSquareIcon,
};

export const ICON_REGISTRY: Record<IconSetId, Record<IconName, IconComponent>> = {
  lucide: LUCIDE,
  tabler: TABLER,
  phosphor: PHOSPHOR,
  heroicons: HERO,
};
