"use client";

import type { ComponentType, SVGProps } from "react";
import {
  Activity,
  ArrowRightLeft,
  Bell,
  Calendar,
  ChartGantt,
  ChevronDown,
  ChevronLeft,
  FolderKanban,
  GripVertical,
  Home,
  Inbox,
  Keyboard,
  List,
  Monitor,
  Moon,
  LayoutDashboard,
  LayoutGrid,
  MessageSquare,
  MoreHorizontal,
  Plus,
  Save,
  LogOut,
  Search,
  Settings,
  Shield,
  SlidersHorizontal,
  Sparkles,
  Sun,
  Tag,
  User,
  Users,
  Volume2,
  Workflow,
  X,
} from "lucide-react";
import {
  IconActivity,
  IconAdjustmentsHorizontal,
  IconArrowsExchange,
  IconBell,
  IconCalendar,
  IconChartBar,
  IconChevronDown,
  IconChevronLeft,
  IconDeviceFloppy,
  IconDots,
  IconFolder,
  IconGripVertical,
  IconHierarchy,
  IconDeviceDesktop,
  IconHome,
  IconInbox,
  IconKeyboard,
  IconList,
  IconMoon,
  IconLayoutDashboard,
  IconLayoutGrid,
  IconMessage,
  IconPlus,
  IconLogout,
  IconSearch,
  IconSettings,
  IconShield,
  IconSparkles,
  IconSun,
  IconTag,
  IconUser,
  IconUsers,
  IconVolume,
  IconX,
} from "@tabler/icons-react";
import {
  Pulse as PhPulse,
  ArrowsLeftRight as PhArrowsLeftRight,
  Bell as PhBell,
  CaretDown as PhCaretDown,
  Calendar as PhCalendar,
  CaretLeft as PhCaretLeft,
  ChartBar as PhChartBar,
  ChatCircle as PhChatCircle,
  DotsSixVertical as PhDotsSixVertical,
  DotsThree as PhDotsThree,
  FloppyDisk as PhFloppyDisk,
  Folder as PhFolder,
  GearSix as PhGearSix,
  GitBranch as PhGitBranch,
  Desktop as PhDesktop,
  House as PhHouse,
  Keyboard as PhKeyboard,
  Layout as PhLayout,
  ListBullets as PhListBullets,
  Moon as PhMoon,
  MagnifyingGlass as PhMagnifyingGlass,
  Plus as PhPlus,
  Shield as PhShield,
  SignOut as PhSignOut,
  SlidersHorizontal as PhSlidersHorizontal,
  Sparkle as PhSparkle,
  Sun as PhSun,
  Tag as PhTag,
  SquaresFour as PhSquaresFour,
  Tray as PhTray,
  User as PhUser,
  Users as PhUsers,
  SpeakerHigh as PhSpeakerHigh,
  X as PhX,
} from "@phosphor-icons/react";
import {
  AdjustmentsHorizontalIcon,
  ArrowDownTrayIcon,
  ArrowPathRoundedSquareIcon,
  ArrowRightCircleIcon,
  ArrowRightStartOnRectangleIcon,
  Bars3Icon,
  BellIcon,
  CalendarDaysIcon,
  ChartBarSquareIcon,
  ChatBubbleLeftIcon,
  ChevronDownIcon,
  CommandLineIcon,
  ComputerDesktopIcon,
  ChevronLeftIcon,
  Cog6ToothIcon,
  FolderIcon,
  HomeIcon,
  InboxIcon,
  ListBulletIcon,
  MagnifyingGlassIcon,
  MoonIcon,
  PlusIcon,
  ShieldCheckIcon,
  SparklesIcon,
  SunIcon,
  TagIcon,
  SpeakerWaveIcon,
  Squares2X2Icon,
  UserIcon,
  UsersIcon,
  XMarkIcon,
} from "@heroicons/react/24/outline";
import type { IconSetId } from "@/lib/appearance/appearance";
import type { IconName } from "@/lib/appearance/icon-names";

export type IconComponent = ComponentType<
  SVGProps<SVGSVGElement> & { className?: string }
>;

function phosphorIcon(
  Icon: ComponentType<{ className?: string; weight?: "regular" }>,
): IconComponent {
  return function PhosphorWrapped({ className }: SVGProps<SVGSVGElement>) {
    return <Icon className={className} weight="regular" />;
  };
}

const LUCIDE: Record<IconName, IconComponent> = {
  "nav.home": Home,
  "nav.board": LayoutGrid,
  "nav.inbox": Inbox,
  "nav.more": MoreHorizontal,
  "nav.pulse": LayoutDashboard,
  "nav.people": Users,
  "nav.notices": Bell,
  "nav.settings": Settings,
  "nav.project": FolderKanban,
  "nav.studios": Activity,
  "action.close": X,
  "action.filter": SlidersHorizontal,
  "action.chevron-down": ChevronDown,
  "action.chevron-left": ChevronLeft,
  "action.plus": Plus,
  "action.search": Search,
  "action.grip": GripVertical,
  "action.move-column": ArrowRightLeft,
  "action.comment": MessageSquare,
  "action.save": Save,
  "action.workflow": Workflow,
  "nav.profile": User,
  "action.sign-out": LogOut,
  "action.lens": Sparkles,
  "action.tag": Tag,
  "action.shield": Shield,
  "action.sun": Sun,
  "action.moon": Moon,
  "action.monitor": Monitor,
  "action.keyboard": Keyboard,
  "view.summary": LayoutDashboard,
  "view.list": List,
  "view.board": LayoutGrid,
  "view.calendar": Calendar,
  "view.timeline": ChartGantt,
  "action.volume": Volume2,
};

const TABLER: Record<IconName, IconComponent> = {
  "nav.home": IconHome,
  "nav.board": IconLayoutGrid,
  "nav.inbox": IconInbox,
  "nav.more": IconDots,
  "nav.pulse": IconLayoutDashboard,
  "nav.people": IconUsers,
  "nav.notices": IconBell,
  "nav.settings": IconSettings,
  "nav.project": IconFolder,
  "nav.studios": IconActivity,
  "action.close": IconX,
  "action.filter": IconAdjustmentsHorizontal,
  "action.chevron-down": IconChevronDown,
  "action.chevron-left": IconChevronLeft,
  "action.plus": IconPlus,
  "action.search": IconSearch,
  "action.grip": IconGripVertical,
  "action.move-column": IconArrowsExchange,
  "action.comment": IconMessage,
  "action.save": IconDeviceFloppy,
  "action.workflow": IconHierarchy,
  "nav.profile": IconUser,
  "action.sign-out": IconLogout,
  "action.lens": IconSparkles,
  "action.tag": IconTag,
  "action.shield": IconShield,
  "action.sun": IconSun,
  "action.moon": IconMoon,
  "action.monitor": IconDeviceDesktop,
  "action.keyboard": IconKeyboard,
  "view.summary": IconLayoutDashboard,
  "view.list": IconList,
  "view.board": IconLayoutGrid,
  "view.calendar": IconCalendar,
  "view.timeline": IconChartBar,
  "action.volume": IconVolume,
};

const PHOSPHOR: Record<IconName, IconComponent> = {
  "nav.home": phosphorIcon(PhHouse),
  "nav.board": phosphorIcon(PhSquaresFour),
  "nav.inbox": phosphorIcon(PhTray),
  "nav.more": phosphorIcon(PhDotsThree),
  "nav.pulse": phosphorIcon(PhLayout),
  "nav.people": phosphorIcon(PhUsers),
  "nav.notices": phosphorIcon(PhBell),
  "nav.settings": phosphorIcon(PhGearSix),
  "nav.project": phosphorIcon(PhFolder),
  "nav.studios": phosphorIcon(PhPulse),
  "action.close": phosphorIcon(PhX),
  "action.filter": phosphorIcon(PhSlidersHorizontal),
  "action.chevron-down": phosphorIcon(PhCaretDown),
  "action.chevron-left": phosphorIcon(PhCaretLeft),
  "action.plus": phosphorIcon(PhPlus),
  "action.search": phosphorIcon(PhMagnifyingGlass),
  "action.grip": phosphorIcon(PhDotsSixVertical),
  "action.move-column": phosphorIcon(PhArrowsLeftRight),
  "action.comment": phosphorIcon(PhChatCircle),
  "action.save": phosphorIcon(PhFloppyDisk),
  "action.workflow": phosphorIcon(PhGitBranch),
  "nav.profile": phosphorIcon(PhUser),
  "action.sign-out": phosphorIcon(PhSignOut),
  "action.lens": phosphorIcon(PhSparkle),
  "action.tag": phosphorIcon(PhTag),
  "action.shield": phosphorIcon(PhShield),
  "action.sun": phosphorIcon(PhSun),
  "action.moon": phosphorIcon(PhMoon),
  "action.monitor": phosphorIcon(PhDesktop),
  "action.keyboard": phosphorIcon(PhKeyboard),
  "view.summary": phosphorIcon(PhLayout),
  "view.list": phosphorIcon(PhListBullets),
  "view.board": phosphorIcon(PhSquaresFour),
  "view.calendar": phosphorIcon(PhCalendar),
  "view.timeline": phosphorIcon(PhChartBar),
  "action.volume": phosphorIcon(PhSpeakerHigh),
};

const HERO: Record<IconName, IconComponent> = {
  "nav.home": HomeIcon,
  "nav.board": Squares2X2Icon,
  "nav.inbox": InboxIcon,
  "nav.more": Bars3Icon,
  "nav.pulse": Squares2X2Icon,
  "nav.people": UsersIcon,
  "nav.notices": BellIcon,
  "nav.settings": Cog6ToothIcon,
  "nav.project": FolderIcon,
  "nav.studios": ArrowPathRoundedSquareIcon,
  "action.close": XMarkIcon,
  "action.filter": AdjustmentsHorizontalIcon,
  "action.chevron-down": ChevronDownIcon,
  "action.chevron-left": ChevronLeftIcon,
  "action.plus": PlusIcon,
  "action.search": MagnifyingGlassIcon,
  "action.grip": Bars3Icon,
  "action.move-column": ArrowRightCircleIcon,
  "action.comment": ChatBubbleLeftIcon,
  "action.save": ArrowDownTrayIcon,
  "action.workflow": ArrowPathRoundedSquareIcon,
  "nav.profile": UserIcon,
  "action.sign-out": ArrowRightStartOnRectangleIcon,
  "action.lens": SparklesIcon,
  "action.tag": TagIcon,
  "action.shield": ShieldCheckIcon,
  "action.sun": SunIcon,
  "action.moon": MoonIcon,
  "action.monitor": ComputerDesktopIcon,
  "action.keyboard": CommandLineIcon,
  "view.summary": Squares2X2Icon,
  "view.list": ListBulletIcon,
  "view.board": Squares2X2Icon,
  "view.calendar": CalendarDaysIcon,
  "view.timeline": ChartBarSquareIcon,
  "action.volume": SpeakerWaveIcon,
};

export const ICON_REGISTRY: Record<IconSetId, Record<IconName, IconComponent>> = {
  lucide: LUCIDE,
  tabler: TABLER,
  phosphor: PHOSPHOR,
  heroicons: HERO,
};
