export const ICON_NAMES = [
  "nav.home",
  "nav.board",
  "nav.inbox",
  "nav.more",
  "nav.pulse",
  "nav.people",
  "nav.notices",
  "nav.settings",
  "nav.project",
  "nav.studios",
  "action.close",
  "action.filter",
  "action.chevron-down",
  "action.chevron-left",
  "action.plus",
  "action.search",
  "action.grip",
  "action.move-column",
  "action.comment",
  "action.save",
  "action.workflow",
  "nav.profile",
  "action.sign-out",
  "action.lens",
  "action.tag",
  "action.shield",
  "action.sun",
  "action.moon",
  "action.monitor",
  "action.keyboard",
  "view.summary",
  "view.list",
  "view.board",
  "view.calendar",
  "view.timeline",
] as const;

export type IconName = (typeof ICON_NAMES)[number];
